spring:
  config:
    activate:
      on-profile: dev
---
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/mystoredb
    username: root
    password: Kiran1309#
    driver-class-name: com.mysql.cj.jdbc.Driver
